// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package com.google.protobuf;

public final class DescriptorProtos {
  private DescriptorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FileDescriptorSet_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_FileDescriptorSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FileDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_FileDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_DescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_DescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_DescriptorProto_ExtensionRange_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_DescriptorProto_ExtensionRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FieldDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_FieldDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_OneofDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_OneofDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_EnumDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_EnumDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_EnumValueDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_EnumValueDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_ServiceDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_ServiceDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_MethodDescriptorProto_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_MethodDescriptorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FileOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_FileOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_MessageOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_MessageOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FieldOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_FieldOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_EnumOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_EnumOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_EnumValueOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_EnumValueOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_ServiceOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_ServiceOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_MethodOptions_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_MethodOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_UninterpretedOption_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_UninterpretedOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_UninterpretedOption_NamePart_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_UninterpretedOption_NamePart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_SourceCodeInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_SourceCodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_SourceCodeInfo_Location_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_SourceCodeInfo_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020descriptor.proto\022\017google.protobuf\"G\n\021F" +
      "ileDescriptorSet\0222\n\004file\030\001 \003(\0132$.google." +
      "protobuf.FileDescriptorProto\"\313\003\n\023FileDes" +
      "criptorProto\022\014\n\004name\030\001 \001(\t\022\017\n\007package\030\002 " +
      "\001(\t\022\022\n\ndependency\030\003 \003(\t\022\031\n\021public_depend" +
      "ency\030\n \003(\005\022\027\n\017weak_dependency\030\013 \003(\005\0226\n\014m" +
      "essage_type\030\004 \003(\0132 .google.protobuf.Desc" +
      "riptorProto\0227\n\tenum_type\030\005 \003(\0132$.google." +
      "protobuf.EnumDescriptorProto\0228\n\007service\030" +
      "\006 \003(\0132\'.google.protobuf.ServiceDescripto",
      "rProto\0228\n\textension\030\007 \003(\0132%.google.proto" +
      "buf.FieldDescriptorProto\022-\n\007options\030\010 \001(" +
      "\0132\034.google.protobuf.FileOptions\0229\n\020sourc" +
      "e_code_info\030\t \001(\0132\037.google.protobuf.Sour" +
      "ceCodeInfo\"\344\003\n\017DescriptorProto\022\014\n\004name\030\001" +
      " \001(\t\0224\n\005field\030\002 \003(\0132%.google.protobuf.Fi" +
      "eldDescriptorProto\0228\n\textension\030\006 \003(\0132%." +
      "google.protobuf.FieldDescriptorProto\0225\n\013" +
      "nested_type\030\003 \003(\0132 .google.protobuf.Desc" +
      "riptorProto\0227\n\tenum_type\030\004 \003(\0132$.google.",
      "protobuf.EnumDescriptorProto\022H\n\017extensio" +
      "n_range\030\005 \003(\0132/.google.protobuf.Descript" +
      "orProto.ExtensionRange\0229\n\noneof_decl\030\010 \003" +
      "(\0132%.google.protobuf.OneofDescriptorProt" +
      "o\0220\n\007options\030\007 \001(\0132\037.google.protobuf.Mes" +
      "sageOptions\032,\n\016ExtensionRange\022\r\n\005start\030\001" +
      " \001(\005\022\013\n\003end\030\002 \001(\005\"\251\005\n\024FieldDescriptorPro" +
      "to\022\014\n\004name\030\001 \001(\t\022\016\n\006number\030\003 \001(\005\022:\n\005labe" +
      "l\030\004 \001(\0162+.google.protobuf.FieldDescripto" +
      "rProto.Label\0228\n\004type\030\005 \001(\0162*.google.prot",
      "obuf.FieldDescriptorProto.Type\022\021\n\ttype_n" +
      "ame\030\006 \001(\t\022\020\n\010extendee\030\002 \001(\t\022\025\n\rdefault_v" +
      "alue\030\007 \001(\t\022\023\n\013oneof_index\030\t \001(\005\022.\n\007optio" +
      "ns\030\010 \001(\0132\035.google.protobuf.FieldOptions\"" +
      "\266\002\n\004Type\022\017\n\013TYPE_DOUBLE\020\001\022\016\n\nTYPE_FLOAT\020" +
      "\002\022\016\n\nTYPE_INT64\020\003\022\017\n\013TYPE_UINT64\020\004\022\016\n\nTY" +
      "PE_INT32\020\005\022\020\n\014TYPE_FIXED64\020\006\022\020\n\014TYPE_FIX" +
      "ED32\020\007\022\r\n\tTYPE_BOOL\020\010\022\017\n\013TYPE_STRING\020\t\022\016" +
      "\n\nTYPE_GROUP\020\n\022\020\n\014TYPE_MESSAGE\020\013\022\016\n\nTYPE" +
      "_BYTES\020\014\022\017\n\013TYPE_UINT32\020\r\022\r\n\tTYPE_ENUM\020\016",
      "\022\021\n\rTYPE_SFIXED32\020\017\022\021\n\rTYPE_SFIXED64\020\020\022\017" +
      "\n\013TYPE_SINT32\020\021\022\017\n\013TYPE_SINT64\020\022\"C\n\005Labe" +
      "l\022\022\n\016LABEL_OPTIONAL\020\001\022\022\n\016LABEL_REQUIRED\020" +
      "\002\022\022\n\016LABEL_REPEATED\020\003\"$\n\024OneofDescriptor" +
      "Proto\022\014\n\004name\030\001 \001(\t\"\214\001\n\023EnumDescriptorPr" +
      "oto\022\014\n\004name\030\001 \001(\t\0228\n\005value\030\002 \003(\0132).googl" +
      "e.protobuf.EnumValueDescriptorProto\022-\n\007o" +
      "ptions\030\003 \001(\0132\034.google.protobuf.EnumOptio" +
      "ns\"l\n\030EnumValueDescriptorProto\022\014\n\004name\030\001" +
      " \001(\t\022\016\n\006number\030\002 \001(\005\0222\n\007options\030\003 \001(\0132!.",
      "google.protobuf.EnumValueOptions\"\220\001\n\026Ser" +
      "viceDescriptorProto\022\014\n\004name\030\001 \001(\t\0226\n\006met" +
      "hod\030\002 \003(\0132&.google.protobuf.MethodDescri" +
      "ptorProto\0220\n\007options\030\003 \001(\0132\037.google.prot" +
      "obuf.ServiceOptions\"\177\n\025MethodDescriptorP" +
      "roto\022\014\n\004name\030\001 \001(\t\022\022\n\ninput_type\030\002 \001(\t\022\023" +
      "\n\013output_type\030\003 \001(\t\022/\n\007options\030\004 \001(\0132\036.g" +
      "oogle.protobuf.MethodOptions\"\253\004\n\013FileOpt" +
      "ions\022\024\n\014java_package\030\001 \001(\t\022\034\n\024java_outer" +
      "_classname\030\010 \001(\t\022\"\n\023java_multiple_files\030",
      "\n \001(\010:\005false\022,\n\035java_generate_equals_and" +
      "_hash\030\024 \001(\010:\005false\022%\n\026java_string_check_" +
      "utf8\030\033 \001(\010:\005false\022F\n\014optimize_for\030\t \001(\0162" +
      ").google.protobuf.FileOptions.OptimizeMo" +
      "de:\005SPEED\022\022\n\ngo_package\030\013 \001(\t\022\"\n\023cc_gene" +
      "ric_services\030\020 \001(\010:\005false\022$\n\025java_generi" +
      "c_services\030\021 \001(\010:\005false\022\"\n\023py_generic_se" +
      "rvices\030\022 \001(\010:\005false\022\031\n\ndeprecated\030\027 \001(\010:" +
      "\005false\022C\n\024uninterpreted_option\030\347\007 \003(\0132$." +
      "google.protobuf.UninterpretedOption\":\n\014O",
      "ptimizeMode\022\t\n\005SPEED\020\001\022\r\n\tCODE_SIZE\020\002\022\020\n" +
      "\014LITE_RUNTIME\020\003*\t\010\350\007\020\200\200\200\200\002\"\323\001\n\016MessageOp" +
      "tions\022&\n\027message_set_wire_format\030\001 \001(\010:\005" +
      "false\022.\n\037no_standard_descriptor_accessor" +
      "\030\002 \001(\010:\005false\022\031\n\ndeprecated\030\003 \001(\010:\005false" +
      "\022C\n\024uninterpreted_option\030\347\007 \003(\0132$.google" +
      ".protobuf.UninterpretedOption*\t\010\350\007\020\200\200\200\200\002" +
      "\"\276\002\n\014FieldOptions\022:\n\005ctype\030\001 \001(\0162#.googl" +
      "e.protobuf.FieldOptions.CType:\006STRING\022\016\n" +
      "\006packed\030\002 \001(\010\022\023\n\004lazy\030\005 \001(\010:\005false\022\031\n\nde",
      "precated\030\003 \001(\010:\005false\022\034\n\024experimental_ma" +
      "p_key\030\t \001(\t\022\023\n\004weak\030\n \001(\010:\005false\022C\n\024unin" +
      "terpreted_option\030\347\007 \003(\0132$.google.protobu" +
      "f.UninterpretedOption\"/\n\005CType\022\n\n\006STRING" +
      "\020\000\022\010\n\004CORD\020\001\022\020\n\014STRING_PIECE\020\002*\t\010\350\007\020\200\200\200\200" +
      "\002\"\215\001\n\013EnumOptions\022\023\n\013allow_alias\030\002 \001(\010\022\031" +
      "\n\ndeprecated\030\003 \001(\010:\005false\022C\n\024uninterpret" +
      "ed_option\030\347\007 \003(\0132$.google.protobuf.Unint" +
      "erpretedOption*\t\010\350\007\020\200\200\200\200\002\"}\n\020EnumValueOp" +
      "tions\022\031\n\ndeprecated\030\001 \001(\010:\005false\022C\n\024unin",
      "terpreted_option\030\347\007 \003(\0132$.google.protobu" +
      "f.UninterpretedOption*\t\010\350\007\020\200\200\200\200\002\"{\n\016Serv" +
      "iceOptions\022\031\n\ndeprecated\030! \001(\010:\005false\022C\n" +
      "\024uninterpreted_option\030\347\007 \003(\0132$.google.pr" +
      "otobuf.UninterpretedOption*\t\010\350\007\020\200\200\200\200\002\"z\n" +
      "\rMethodOptions\022\031\n\ndeprecated\030! \001(\010:\005fals" +
      "e\022C\n\024uninterpreted_option\030\347\007 \003(\0132$.googl" +
      "e.protobuf.UninterpretedOption*\t\010\350\007\020\200\200\200\200" +
      "\002\"\236\002\n\023UninterpretedOption\022;\n\004name\030\002 \003(\0132" +
      "-.google.protobuf.UninterpretedOption.Na",
      "mePart\022\030\n\020identifier_value\030\003 \001(\t\022\032\n\022posi" +
      "tive_int_value\030\004 \001(\004\022\032\n\022negative_int_val" +
      "ue\030\005 \001(\003\022\024\n\014double_value\030\006 \001(\001\022\024\n\014string" +
      "_value\030\007 \001(\014\022\027\n\017aggregate_value\030\010 \001(\t\0323\n" +
      "\010NamePart\022\021\n\tname_part\030\001 \002(\t\022\024\n\014is_exten" +
      "sion\030\002 \002(\010\"\261\001\n\016SourceCodeInfo\022:\n\010locatio" +
      "n\030\001 \003(\0132(.google.protobuf.SourceCodeInfo" +
      ".Location\032c\n\010Location\022\020\n\004path\030\001 \003(\005B\002\020\001\022" +
      "\020\n\004span\030\002 \003(\005B\002\020\001\022\030\n\020leading_comments\030\003 " +
      "\001(\t\022\031\n\021trailing_comments\030\004 \001(\tB4\n\023com.go",
      "ogle.protobufB\020DescriptorProtosH\001P\001\200\001\001\210\001" +
      "\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_FileDescriptorSet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_FileDescriptorSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_FileDescriptorSet_descriptor,
        new java.lang.String[] { "File", });
    internal_static_google_protobuf_FileDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_FileDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_FileDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Package", "Dependency", "PublicDependency", "WeakDependency", "MessageType", "EnumType", "Service", "Extension", "Options", "SourceCodeInfo", });
    internal_static_google_protobuf_DescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_DescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_DescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Field", "Extension", "NestedType", "EnumType", "ExtensionRange", "OneofDecl", "Options", });
    internal_static_google_protobuf_DescriptorProto_ExtensionRange_descriptor =
      internal_static_google_protobuf_DescriptorProto_descriptor.getNestedTypes().get(0);
    internal_static_google_protobuf_DescriptorProto_ExtensionRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_DescriptorProto_ExtensionRange_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_google_protobuf_FieldDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_protobuf_FieldDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_FieldDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Number", "Label", "Type", "TypeName", "Extendee", "DefaultValue", "OneofIndex", "Options", });
    internal_static_google_protobuf_OneofDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_protobuf_OneofDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_OneofDescriptorProto_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_protobuf_EnumDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_protobuf_EnumDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_EnumDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Value", "Options", });
    internal_static_google_protobuf_EnumValueDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_protobuf_EnumValueDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_EnumValueDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Number", "Options", });
    internal_static_google_protobuf_ServiceDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_protobuf_ServiceDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_ServiceDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "Method", "Options", });
    internal_static_google_protobuf_MethodDescriptorProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_protobuf_MethodDescriptorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_MethodDescriptorProto_descriptor,
        new java.lang.String[] { "Name", "InputType", "OutputType", "Options", });
    internal_static_google_protobuf_FileOptions_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_protobuf_FileOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_FileOptions_descriptor,
        new java.lang.String[] { "JavaPackage", "JavaOuterClassname", "JavaMultipleFiles", "JavaGenerateEqualsAndHash", "JavaStringCheckUtf8", "OptimizeFor", "GoPackage", "CcGenericServices", "JavaGenericServices", "PyGenericServices", "Deprecated", "UninterpretedOption", });
    internal_static_google_protobuf_MessageOptions_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_protobuf_MessageOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_MessageOptions_descriptor,
        new java.lang.String[] { "MessageSetWireFormat", "NoStandardDescriptorAccessor", "Deprecated", "UninterpretedOption", });
    internal_static_google_protobuf_FieldOptions_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_protobuf_FieldOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_FieldOptions_descriptor,
        new java.lang.String[] { "Ctype", "Packed", "Lazy", "Deprecated", "ExperimentalMapKey", "Weak", "UninterpretedOption", });
    internal_static_google_protobuf_EnumOptions_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_protobuf_EnumOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_EnumOptions_descriptor,
        new java.lang.String[] { "AllowAlias", "Deprecated", "UninterpretedOption", });
    internal_static_google_protobuf_EnumValueOptions_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_protobuf_EnumValueOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_EnumValueOptions_descriptor,
        new java.lang.String[] { "Deprecated", "UninterpretedOption", });
    internal_static_google_protobuf_ServiceOptions_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_protobuf_ServiceOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_ServiceOptions_descriptor,
        new java.lang.String[] { "Deprecated", "UninterpretedOption", });
    internal_static_google_protobuf_MethodOptions_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_protobuf_MethodOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_MethodOptions_descriptor,
        new java.lang.String[] { "Deprecated", "UninterpretedOption", });
    internal_static_google_protobuf_UninterpretedOption_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_protobuf_UninterpretedOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_UninterpretedOption_descriptor,
        new java.lang.String[] { "Name", "IdentifierValue", "PositiveIntValue", "NegativeIntValue", "DoubleValue", "StringValue", "AggregateValue", });
    internal_static_google_protobuf_UninterpretedOption_NamePart_descriptor =
      internal_static_google_protobuf_UninterpretedOption_descriptor.getNestedTypes().get(0);
    internal_static_google_protobuf_UninterpretedOption_NamePart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_UninterpretedOption_NamePart_descriptor,
        new java.lang.String[] { "NamePart", "IsExtension", });
    internal_static_google_protobuf_SourceCodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_protobuf_SourceCodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_SourceCodeInfo_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_google_protobuf_SourceCodeInfo_Location_descriptor =
      internal_static_google_protobuf_SourceCodeInfo_descriptor.getNestedTypes().get(0);
    internal_static_google_protobuf_SourceCodeInfo_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_SourceCodeInfo_Location_descriptor,
        new java.lang.String[] { "Path", "Span", "LeadingComments", "TrailingComments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
